services:
  - type: web
    name: fonoaudiologia
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        value: ep-dawn-bread-aydb0mvz-pooler.c-5.us-east-2.aws.neon.tech
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASS
        sync: false
      - key: JWT_SECRET
        generateValue: true
    plan: free
